#
# NOTE: THIS DOCKERFILE IS GENERATED BY JUAN LIU 2017.04.17
# littlewei_liu@163.com
# PLEASE DO NOT EDIT IT DIRECTLY.
#
FROM suifengdeshitou/appium-cartierej-android:base

#=======================================
# app.sh include adb connect & appium
# and client case
# if you want change app_shell to other
# name, you need to change app_shell to
# other name in generator.py around line 65
#=======================================
RUN mkdir /app_shell
COPY ./app.sh /app_shell/
RUN chmod 777 /app_shell/app.sh

#=======================================
# install python2.7
#=======================================
RUN apt-get update && apt-get install python2.7 && apt-get install -y python-pip

#=======================================
# set the localtime (option)
#=======================================
RUN echo "Asia/shanghai" > /etc/timezone && \
    cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

#=======================================
# pull code from git
#=======================================

RUN git clone https://github.com/haifengrundadi/CartierEJ.git

WORKDIR CartierEJ

RUN pip install -r requirements.txt

RUN mkdir logs

WORKDIR tests/smoketest

CMD ["bash /app_shell/app.sh]
